version: '2'
services:
  test:
    build:
      context: git@github.com:CodeNow/runnable-angular.git
      Dockerfile: Dockerfile.test
      environment:
        RACK_ENV: development
        SHOW: 'true'
        SESSION_SECRET:


