version: '2'
services:
  test:
    build:
      context: git@github.com:CodeNow/runnable-angular.git
      Dockerfile: Dockerfile.test
      ports:
       - "3000"
       - "3000-3005"
       - "8000:8000"


